from utils import *


def propeller_power(pbr, nu_p, nu_g, hp=False):
    """
    Propeller required power
    :param pbr: Propeller power
    :param nu_p: Propeller spool efficiency
    :param nu_g: Propeller gearbox efficiency
    :param hp: Propeller power in horse power
    :return: Work required by the flow on turbine
    """
    if hp is True:
        pbr = pbr*0.735499*1000
    print(units('Ẇ_prop = {:,.4f}'.format(pbr/(nu_p*nu_g)), 'W'))
    return pbr/(nu_p*nu_g)


def propeller_thrust(w, nu, v0):
    """
    Thrust generated by propeller
    :param w: Propeller power
    :param nu: Propeller mechanical efficiency
    :param v0: Free stream velocity
    :return:
    """
    print(units('T_prop = {:,.4f}'.format(nu*w/v0), 'W'))
    return nu*w/v0